# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: chat.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto
from protobunny import models as models


@dataclass(eq=False, repr=False)
class ChatMessage(models.ProtoBunnyMessage):
    sender: str = betterproto.string_field(1)
    content: str = betterproto.string_field(2)
    to_user: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class UserStatus(models.ProtoBunnyMessage):
    client_id: str = betterproto.string_field(1)
    online: bool = betterproto.bool_field(2)
