# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tasks.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto
from protobunny import models as models

from .. import chat as _chat__


@dataclass(eq=False, repr=False)
class ArchiveMessage(models.ProtoBunnyMessage):
    message: "_chat__.ChatMessage" = betterproto.message_field(1)
